### ISSUE TITLE
Cannot find Vitis

### ISSUE THREAD

**Issue by ChunshuWu** [OCT-FPGA/Vitis-Tutorials-U280#1]
Hello, 

I've joined the OCTFPGA project and requested a node with the following parameter settings
![image](https://user-images.githubusercontent.com/69404759/210646479-cebb54fc-8c02-4617-b90d-773799eb9e35.png)

I tried to follow the tutorial in this repository, but I could not find the path to Vitis, and the path _/tools/Xilinx/Vitis/2020.1/settings64.sh_ does not exist. Besides, most of the links in _vitis-getting-started-moc.md_ are 404. 

I also searched for vitis on the node I requested
`find / -name "vitis"`
 but nothing was found. Is there a way to set up the environment now on the server? Thanks!

**Comment by surangamh** [comment]
Hi,

Thanks for your question.

There are two parts in the OCT workflow. 1. Development, 2. Deployment. Deployment of FPGA bitstreams is done on an FPGA cluster in CloudLab by creating an experiment like you did. Up until recently, OCT users were using Mass Open Cloud ([MOC](https://massopen.cloud/)) for development. However, this is no longer supported as we are in the process of migrating the build workflow into CloudLab. The source command that you mentioned should be run on a build machine that has a Vitis image (this used to be an MOC instance), which the CloudLab node that you set up doesn't have. It is only used to deploy your bitstream. 

If you need a build machine and don't have one yet, I can provide you one. Please send an email to s.handagala@northeastern.edu with the following details. 

1. Your name and affiliation
2. Name of the faculty advisor
3. Name of the project

Thanks,
Suranga
